name: PR_checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build for macOS
      run: swift build -v

    - name: Run unit tests for macOS
      run: swift test -v

    - name: Run iOS tests
      run: ./Scripts/run_unit_tests_on_ios.sh
