name: PR_checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build for macOS
      run: swift build -v

    - name: Run unit tests for macOS
      run: swift test -v

    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme Network-Package -destination "platform=iOS Simulator,OS=latest,name=iPhone 14" | xcpretty
  
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme Network-Package -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
